# Startup programs
# -------------------------------------------------------------------

# Graphics, Themes & Hardware Control
exec --no-startup-id sh ~/.fehbg                                    
exec --no-startup-id xrdb -merge ~/.Xresources                     
exec_always --no-startup-id picom --config ~/.config/picom/picom.conf
exec_always --no-startup-id numlockx on
exec --no-startup-id light -s sysfs/leds/smc::kbd_backlight -S 20

# Automated Themes (Pywal & Polybar)
exec --no-startup-id ~/.config/i3/scripts/py-walls.sh
exec_always killall polybar
exec_always --no-startup-id "wal -R && $HOME/.config/polybar/polybar.sh"

# Screen Locking, Idle & Power Management
exec --no-startup-id xautolock -time 5 -locker 'betterlockscreen -l dim' -detectsleep -corners "+---" -cornerdelay 5 -notify 5 -notifier "~/.config/i3/scripts/lockscreen-notify.sh"
exec --no-startup-id ~/.config/i3/scripts/betterlockscreen.sh
exec --no-startup-id xset s 420 dpms 420 420 420                   

# Daemons & Background Services
exec_always --no-startup-id ~/.config/i3/scripts/dunst.sh
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id blueman-applet                                 
exec_always --no-startup-id autotiling
exec --no-startup-id ~/.config/i3/scripts/battery-monitor.sh

# User Notifications
exec --no-startup-id ~/.config/i3/scripts/notify-send.sh "Welcome back $USER!" -i ~/.images/icons8-user-100.png
