# =====================================================================
# WINDOW MANAGMENT & TYPOGRAPHY
# =====================================================================

# Font configuration for window title bars
font pango:Roboto Bold 10

# Mouse behavior for floating windows
floating_modifier     $mod
floating_minimum_size 300 x 300
floating_maximum_size -1 x -1

# Focus & Layout options
workspace_layout    default
focus_follows_mouse no

# =====================================================================
# WINDOW GAPS STYLING (i3-gaps)
# =====================================================================
gaps inner 6
gaps outer 3

# Smart behaviors (hide gaps/borders if there is only one window)
smart_gaps    on
smart_borders on

# =====================================================================
# INTERACTIVE GAPS CONTROL MODES
# =====================================================================
set $mode_gaps       Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +|-|0 (local), Shift + +|-|0 (global)
set $mode_gaps_inner Inner Gaps: +|-|0 (local), Shift + +|-|0 (global)

bindsym $mod+Shift+g mode "$mode_gaps"

# --- Main Gaps Menu ---
mode "$mode_gaps" {
    bindsym o            mode "$mode_gaps_outer"
    bindsym i            mode "$mode_gaps_inner"
    
    # Exit options
    bindsym Return       mode "default"
    bindsym Escape       mode "default"
    bindsym $mod+Shift+g mode "default"
}

# --- Inner Gaps Menu ---
mode "$mode_gaps_inner" {
    # Local workspace alterations
    bindsym plus        gaps inner current plus 5
    bindsym minus       gaps inner current minus 5
    bindsym 0           gaps inner current set 0

    # Global workspace alterations
    bindsym Shift+plus  gaps inner all plus 5
    bindsym Shift+minus gaps inner all minus 5
    bindsym Shift+0     gaps inner all set 0

    # Exit options
    bindsym Return       mode "default"
    bindsym Escape       mode "default"
    bindsym $mod+Shift+g mode "default"
}

# --- Outer Gaps Menu ---
mode "$mode_gaps_outer" {
    # Local workspace alterations
    bindsym plus        gaps outer current plus 5
    bindsym minus       gaps outer current minus 5
    bindsym 0           gaps outer current set 0

    # Global workspace alterations
    bindsym Shift+plus  gaps outer all plus 5
    bindsym Shift+minus gaps outer all minus 5
    bindsym Shift+0     gaps outer all set 0

    # Exit options
    bindsym Return       mode "default"
    bindsym Escape       mode "default"
    bindsym $mod+Shift+g mode "default"
}