
# Core Colors
background            #19120d
foreground            #f0dfd6
selection_foreground  #ffb781
selection_background  #4e2500
cursor                #ffb781
cursor_text_color     #19120d

# Regular Colors
color0  #19120d               
color1  #ffb4ab                 
color2  #ffb781               
color3  #c7ca95              
color4  #ffdcc4  
color5  #ffdcc4
color6  #e4bfa7             
color7  #f0dfd6            

# Bright Colors
color8  #413731         
color9  #ffb4ab                  
color10 #ffb781                
color11 #c7ca95               
color12 #ffdcc4   
color13 #ffdcc4 
color14 #e4bfa7              
color15 #f0dfd6   
