$image = /home/saad/dotspace/niri/wallpapers/3.png

$background = rgba(19120dff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(382f28ff)

$inverse_primary = rgba(895020ff)

$inverse_surface = rgba(f0dfd6ff)

$on_background = rgba(f0dfd6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(4e2500ff)

$on_primary_container = rgba(ffdcc4ff)

$on_primary_fixed = rgba(2f1400ff)

$on_primary_fixed_variant = rgba(6d3a09ff)

$on_secondary = rgba(422b1aff)

$on_secondary_container = rgba(ffdcc4ff)

$on_secondary_fixed = rgba(2a1708ff)

$on_secondary_fixed_variant = rgba(5b412fff)

$on_surface = rgba(f0dfd6ff)

$on_surface_variant = rgba(d6c3b7ff)

$on_tertiary = rgba(2f330cff)

$on_tertiary_container = rgba(e3e7afff)

$on_tertiary_fixed = rgba(1b1d00ff)

$on_tertiary_fixed_variant = rgba(464a20ff)

$outline = rgba(9f8d83ff)

$outline_variant = rgba(52443bff)

$primary = rgba(ffb781ff)

$primary_container = rgba(6d3a09ff)

$primary_fixed = rgba(ffdcc4ff)

$primary_fixed_dim = rgba(ffb781ff)

$scrim = rgba(000000ff)

$secondary = rgba(e4bfa7ff)

$secondary_container = rgba(5b412fff)

$secondary_fixed = rgba(ffdcc4ff)

$secondary_fixed_dim = rgba(e4bfa7ff)

$shadow = rgba(000000ff)

$source_color = rgba(f9a15bff)

$surface = rgba(19120dff)

$surface_bright = rgba(413731ff)

$surface_container = rgba(261e18ff)

$surface_container_high = rgba(312822ff)

$surface_container_highest = rgba(3c332dff)

$surface_container_low = rgba(221a14ff)

$surface_container_lowest = rgba(140d08ff)

$surface_dim = rgba(19120dff)

$surface_tint = rgba(ffb781ff)

$surface_variant = rgba(52443bff)

$tertiary = rgba(c7ca95ff)

$tertiary_container = rgba(464a20ff)

$tertiary_fixed = rgba(e3e7afff)

$tertiary_fixed_dim = rgba(c7ca95ff)

